### ISSUE TITLE
权重加载问题

### ISSUE THREAD

**Issue by superyq-create** [Shawn-Yu-1/MAT#1]
您好，这个工作解决了cuda编译的问题，请问一下这个项目可以直接加载原论文网址的权重吗，在推理512*512图像速度会慢多少呢

**Comment by Shawn-Yu-1** [comment]
这个时间有点长了，我记不清有没有试过加载预训练的权重。应该是可以的，你只要改一下权重加载的代码，手动加载改过的模块的权重。

Xiankang Yu
________________________________
发件人: Yangnengqun ***@***.***>
发送时间: 2024年9月6日 18:36
收件人: Shawn-Yu-1/MAT ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Shawn-Yu-1/MAT] 权重加载问题 (Issue #1)


您好，这个工作解决了cuda编译的问题，请问一下这个项目可以直接加载原论文网址的权重吗，在推理512*512图像速度会慢多少呢

―
