### ISSUE TITLE
torch_utils is missing, test scripts cannot be used

### ISSUE THREAD

**Issue by lipenghuai** [Shawn-Yu-1/MAT#2]
torch_utils is missing, test scripts cannot be used
ModuleNotFoundError: No module named 'torch_utils‘

**Comment by Shawn-Yu-1** [comment]
Could you tell me which file has the error,I don't find any files has called "test".

**Comment by lipenghuai** [comment]
Sorry, I confused your file with the original code. Thank you for providing the code.
I would be very grateful if you could upload the log.txt file during training, because some parameters in it are not very clear.

**Comment by Shawn-Yu-1** [comment]
Never mind,but it was two years ago,I maybe delete the logs.
